language: rust

after_success:
  - curl https://stainless-steel.github.io/travis/after_success.sh | bash

env:
  global:
    secure: n8xBAiaI23myxhJWLfSTvScCB3ccUhwPOM4FhpOT/b5vtp1UKUXbp69I9uT5J90VmHuJ/vnEmW73JjgnDLgNEvy8tw4zDVFkEDDANahQvaEYUEC5MwLDU/C7JBpuIWE8pShba4NQQ1ieNwVoJVkIsIJ5X95QICDwrgOhOPbq+gpRqdSxzPa8i5rsQ2YQpefawd72UHymRXqJyhTg7ZnipQaT2UBlPjQ8zA49hc/eB9jDnGqMHmgdUMvoKVkakRaKvyysBDDfWuytdh1gz6lxfEtFKqWBDgwC0HATzTbvZVS1CiNtE3mZ/zO4TRTlsVwHsCC6c1TDckBAjM62nOqorIVxO+MnVbWwWLrC0vC8BraaQi7kFn/6cisFhs+qb1OSo9zN9maNUtH/fLT2VTgIruQdAMlKW7pOOvR/DUveyxddr1jakYPUudiJ2RKP6l46GNtlDAhfv11IGDPzVAAj+0uH4yz1WKLVIPae9rXo3zbX8gCVKqLdcyzt52woP8AaLbiBRtB2OmBjhQRMBZk82yEhqAN0AM/Jzj9/QSnlUqpQZ9T9Zhvviqj76YYQ8iFj7J/ervYBMsxvCpuDt7/JKH20pN0n/If63NLUf2Xo0v8D4KPZEuslT0l00k64qw5V0q2QPKYv/aNzknOHXwGclxDT03OXLskv4Gjc4VNfwAU=

notifications:
  email: false
