[package]
name = "superlu-sys"
version = "0.3.0"
license = "Apache-2.0/MIT"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
description = "The package provides bindings to SuperLU."
documentation = "https://stainless-steel.github.io/superlu-sys"
homepage = "https://github.com/stainless-steel/superlu-sys"
repository = "https://github.com/stainless-steel/superlu-sys"
build = "build.rs"
links = "superlu"

[dependencies]
blas-sys = "0.6"
libc = "0.2"
