[package]
name = "superlu-sys"
version = "0.2.4"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/superlu-sys"
homepage = "https://github.com/stainless-steel/superlu-sys"
documentation = "https://stainless-steel.github.io/superlu-sys"
description = "The package provides bindings to SuperLU."
build = "build.rs"
links = "superlu"

[dependencies]
blas-sys = "0.5"
libc = "0.2"
